"""password

Revision ID: 6eb3a477fbc4
Revises: 58ac84899d92
Create Date: 2024-07-13 20:14:54.278734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb3a477fbc4'
down_revision = '58ac84899d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
